<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/by-status/delayed
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
import Timeline from '$lib/Components/Templates/Timeline.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Projects that have exceeded their projected timelines.`}
  </div>
  <Table props={data} />
  <Filter props={data} />
  <Timeline props={data} />
</div>
