<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /local-gov/legislative/meetings
  export let data: any;

import Calendar from '$lib/Components/Templates/Calendar.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `View the schedule of legislative meetings.`}
  </div>
  <Calendar props={data} />
  <Info props={data} />
</div>
