<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /health-welfare/social-welfare/pwd
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Programs and benefits for Persons with Disabilities.`}
  </div>
  <Info props={data} />
  <Form props={data} />
</div>
