<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /education/sk-federation/projects
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `View ongoing and completed projects of the SK Federation.`}
  </div>
  <Table props={data} />
  <Info props={data} />
</div>
