<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /saln-declarations/by-agency
  export let data: any;

import Accordion from '$lib/Components/Templates/Accordion.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Browse SALN submissions from officials grouped by their respective government agencies.`}
  </div>
  <Accordion props={data} />
  <Table props={data} />
  <Filter props={data} />
</div>
