<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/by-status/flagged
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
import Alert from '$lib/Components/Templates/Alert.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Projects flagged for potential issues, anomalies, or corruption indicators.`}
  </div>
  <Table props={data} />
  <Filter props={data} />
  <Alert props={data} />
</div>
