<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /health-welfare/health-services
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Access RHU services and manage your health records.`}
  </div>
  <Dashboard props={data} />
  <Form props={data} />
</div>
