<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /intel-command/ci-management
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Secure, encrypted registry for informant handling, validation, and intelligence reporting.`}
  </div>
  <Form props={data} />
  <Table props={data} />
  <Profile props={data} />
</div>
