<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/mandate/investigation-scope
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Accordion from '$lib/Components/Templates/Accordion.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Defines the areas and types of projects ICI investigates.`}
  </div>
  <Info props={data} />
  <Accordion props={data} />
</div>
