<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /local-gov/legislative/ordinances
  export let data: any;

import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
import Search from '$lib/Components/Templates/Search.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `View and search for local ordinances and resolutions.`}
  </div>
  <DocumentHub props={data} />
  <Search props={data} />
</div>
