<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /intel-command/fusion-analytics-center/financial-intelligence
  export let data: any;

import Chart from '$lib/Components/Templates/Chart.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Track and disrupt money laundering networks through banks and cryptocurrency.`}
  </div>
  <Chart props={data} />
  <Table props={data} />
  <Report props={data} />
</div>
