<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /public-info/news-media/miscellaneous
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `General news and information that is not category-specific.`}
  </div>
  <Dashboard props={data} />
  <Info props={data} />
</div>
