<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/incident-report/track-report
  export let data: any;

import Tracker from '$lib/Components/Templates/Tracker.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Monitor the status of your submitted reports.`}
  </div>
  <Tracker props={data} />
  <Table props={data} />
</div>
