<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /operations-command/special-units
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
import Gps from '$lib/Components/Templates/Gps.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Manage K-9 Teams, Special Reaction Units (SRU), and Aviation assets.`}
  </div>
  <Dashboard props={data} />
  <Table props={data} />
  <Info props={data} />
  <Gps props={data} />
</div>
