// Auto-generated by project_EngineerV2.ts on Wed Sep 24 2025 13:10:00 GMT+0800 (Philippine Standard Time)
// This file contains the site's navigation structure and metadata for build-time import.

export const siteInfo = {
  "targetPath": "PDEA",
  "friendlyName": "Philippine Drug Enforcement Agency"
};

export const navigation = [
  {
    "slug": "intel-command",
    "navTitle": "INTELCOM",
    "icon": "BrainCircuit",
    "description": "The nerve center for multi-source data fusion, predictive analysis, and actionable intelligence generation.",
    "children": [
      {
        "slug": "intel-command/target-dossiers",
        "navTitle": "HVTs",
        "icon": "Target",
        "description": "Dynamic profiles of HVTs, syndicates, and their networks, updated in real-time."
      },
      {
        "slug": "intel-command/fusion-analytics-center",
        "navTitle": "Analytics",
        "icon": "Network",
        "description": "AI-driven tools for deep analysis across multiple intelligence disciplines.",
        "children": [
          {
            "slug": "intel-command/fusion-analytics-center/geospatial-intelligence",
            "navTitle": "GEOINT",
            "icon": "Map",
            "description": "Map and analyze drug routes, clandestine laboratories, and operational hotspots."
          },
          {
            "slug": "intel-command/fusion-analytics-center/financial-intelligence",
            "navTitle": "FININT",
            "icon": "Bitcoin",
            "description": "Track and disrupt money laundering networks through banks and cryptocurrency."
          },
          {
            "slug": "intel-command/fusion-analytics-center/cyber-intelligence",
            "navTitle": "CYBINT",
            "icon": "Laptop",
            "description": "Monitor darknet markets, encrypted communications, and online narcotics trafficking."
          }
        ]
      },
      {
        "slug": "intel-command/ci-management",
        "navTitle": "CIs",
        "icon": "UserCog",
        "description": "Secure, encrypted registry for informant handling, validation, and intelligence reporting."
      }
    ]
  },
  {
    "slug": "operations-command",
    "navTitle": "OPSCOM",
    "icon": "Crosshair",
    "description": "Plan, authorize, and command all national and regional counter-narcotics field operations.",
    "children": [
      {
        "slug": "operations-command/rtoc",
        "navTitle": "RTOC",
        "icon": "Satellite",
        "description": "Live situational awareness and command & control for all active missions."
      },
      {
        "slug": "operations-command/field-operations-log",
        "navTitle": "Ops Log",
        "icon": "BookCopy",
        "description": "Comprehensive repository of all planned, ongoing, and completed field operations.",
        "children": [
          {
            "slug": "operations-command/field-operations-log/buy-bust-ops",
            "navTitle": "Buy-Bust",
            "icon": "Handshake",
            "description": "Manage and track all buy-bust operations nationwide."
          },
          {
            "slug": "operations-command/field-operations-log/interdiction-ops",
            "navTitle": "Interdiction",
            "icon": "Ship",
            "description": "Log operations at seaports, airports, and mail/parcel services."
          }
        ]
      },
      {
        "slug": "operations-command/special-units",
        "navTitle": "Special Units",
        "icon": "Dog",
        "description": "Manage K-9 Teams, Special Reaction Units (SRU), and Aviation assets."
      }
    ]
  },
  {
    "slug": "investigations-legal",
    "navTitle": "Investigation",
    "icon": "Gavel",
    "description": "Build airtight cases against drug offenders from arrest to prosecution, ensuring legal compliance.",
    "children": [
      {
        "slug": "investigations-legal/unified-case-management",
        "navTitle": "Cases",
        "icon": "FolderSearch",
        "description": "The central system for all case files, events, and linked entities from initiation to resolution.",
        "children": [
          {
            "slug": "investigations-legal/unified-case-management/hvt-cases",
            "navTitle": "HVT Cases",
            "icon": "UserCheck",
            "description": "Specialized tracking for cases involving top-tier drug personalities."
          },
          {
            "slug": "investigations-legal/unified-case-management/syndicate-cases",
            "navTitle": "Syndicate Cases",
            "icon": "Users",
            "description": "Investigations focused on dismantling entire drug trafficking organizations."
          }
        ]
      },
      {
        "slug": "investigations-legal/prosecution-support",
        "navTitle": "DOJ Support",
        "icon": "Landmark",
        "description": "Prepare and transmit evidence packages and case summaries to the Department of Justice."
      }
    ]
  },
  {
    "slug": "forensics-evidence",
    "navTitle": "Forensics",
    "icon": "Microscope",
    "description": "Ensure the scientific and legal integrity of all seized evidence from collection to court presentation.",
    "children": [
      {
        "slug": "forensics-evidence/dcoc",
        "navTitle": "Chain of Custody",
        "icon": "Link",
        "description": "Immutable, tamper-proof log for all evidence handling, compliant with R.A. 9165."
      },
      {
        "slug": "forensics-evidence/laboratory-services",
        "navTitle": "Labs",
        "icon": "FlaskConical",
        "description": "Manage drug testing, chemical analysis, and results from forensic chemistry labs."
      },
      {
        "slug": "forensics-evidence/digital-forensics-unit",
        "navTitle": "Digital Forensics",
        "icon": "Fingerprint",
        "description": "Extract and analyze evidence from seized digital devices and cryptocurrency wallets.",
        "children": [
          {
            "slug": "forensics-evidence/digital-forensics-unit/mobile-forensics",
            "navTitle": "Mobile",
            "icon": "Smartphone",
            "description": "Case management for analysis of seized mobile phones and tablets."
          },
          {
            "slug": "forensics-evidence/digital-forensics-unit/computer-forensics",
            "navTitle": "Computer",
            "icon": "Server",
            "description": "Case management for analysis of seized laptops, desktops, and servers."
          }
        ]
      }
    ]
  },
  {
    "slug": "strategic-command",
    "navTitle": "STRATCOM",
    "icon": "Shield",
    "description": "High-level policy support, asset forfeiture, and seamless collaboration with local and international partners.",
    "children": [
      {
        "slug": "strategic-command/asset-forfeiture",
        "navTitle": "Asset Forfeiture",
        "icon": "Banknote",
        "description": "Track financial investigations with AMLC and manage seized assets from drug syndicates."
      },
      {
        "slug": "strategic-command/inter-agency-portal",
        "navTitle": "Task Forces",
        "icon": "Users2",
        "description": "Secure collaboration portals for joint task forces with PNP, NBI, AFP, and foreign partners.",
        "children": [
          {
            "slug": "strategic-command/inter-agency-portal/task-force-local",
            "navTitle": "Local TF",
            "icon": "UserCog",
            "description": "Joint operations planning and intelligence sharing with local law enforcement."
          },
          {
            "slug": "strategic-command/inter-agency-portal/international-liaison",
            "navTitle": "Int'l Liaison",
            "icon": "Globe",
            "description": "Secure communication channel for coordinating with international partners."
          }
        ]
      }
    ]
  },
  {
    "slug": "directory",
    "navTitle": "Directory",
    "icon": "BookUser",
    "description": "Find office locations, contact personnel, and view our service commitments.",
    "children": [
      {
        "slug": "directory/office-locations",
        "navTitle": "Locations",
        "icon": "MapPinned",
        "description": "Interactive map and list of all PDEA regional offices nationwide."
      },
      {
        "slug": "directory/key-officials",
        "navTitle": "Officials",
        "icon": "Users",
        "description": "Directory of the PDEA Director General, Deputy DGs, and Service Directors."
      },
      {
        "slug": "directory/citizens-charter",
        "navTitle": "Charter",
        "icon": "ShieldCheck",
        "description": "View our service standards for clearances, reporting, and other public services."
      }
    ]
  }
];
