<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import KpiDeck from '$lib/Components/Templates/KpiDeck.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Monitor the status, budget, and progress of all registered public infrastructure projects across the Philippines.`}
  </div>
  <Map props={data} />
  <KpiDeck props={data} />
  <Table props={data} />
  <Filter props={data} />
</div>
