<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/emergency-alerts/hazard-maps
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Interactive maps showing real-time hazards and affected areas.`}
  </div>
  <Map props={data} />
  <Info props={data} />
</div>
