<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigations-legal/unified-case-management
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `The central system for all case files, events, and linked entities from initiation to resolution.`}
  </div>
  <Dashboard props={data} />
  <Table props={data} />
  <Tracker props={data} />
</div>
