<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services/community-feedback/citizen-concerns
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Report issues and concerns on LGU services or staff.`}
  </div>
  <Form props={data} />
</div>
