<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /directory/citizens-charter
  export let data: any;

import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `View our service standards for clearances, reporting, and other public services.`}
  </div>
  <DocumentHub props={data} />
  <Report props={data} />
</div>
