<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /soundboard
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Chat from '$lib/Components/Templates/Chat.svelte';
import Faq from '$lib/Components/Templates/Faq.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `A platform for citizen engagement, feedback, and whistleblowing.`}
  </div>
  <Form props={data} />
  <Table props={data} />
  <Chat props={data} />
  <Faq props={data} />
</div>
