<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /health-welfare/social-welfare/4ps
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Information on the Pantawid Pamilyang Pilipino Program (4Ps).`}
  </div>
  <Info props={data} />
  <Report props={data} />
</div>
