<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/incident-report/submit-report
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Camera from '$lib/Components/Templates/Camera.svelte';
import Gps from '$lib/Components/Templates/Gps.svelte';
import Upload from '$lib/Components/Templates/Upload.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Submit a report with your location, photos, and videos.`}
  </div>
  <Form props={data} />
  <Camera props={data} />
  <Gps props={data} />
  <Upload props={data} />
</div>
