<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/history/formation
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Timeline from '$lib/Components/Templates/Timeline.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Details on the establishment and legal foundations of ICI.`}
  </div>
  <Info props={data} />
  <Timeline props={data} />
</div>
