<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /dashboard/live-alerts
  export let data: any;

import Feed from '$lib/Components/Templates/Feed.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
import Reminder from '$lib/Components/Templates/Reminder.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Real-time notifications and alerts regarding infrastructure issues or anomalies.`}
  </div>
  <Feed props={data} />
  <Filter props={data} />
  <Reminder props={data} />
</div>
