<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/leadership/secretariat
  export let data: any;

import Profile from '$lib/Components/Templates/Profile.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Supporting staff and the secretariat team.`}
  </div>
  <Profile props={data} />
  <Info props={data} />
</div>
