<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /education/sk-federation
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Official announcements and programs from the Sangguniang Kabataan Federation.`}
  </div>
  <Dashboard props={data} />
  <Info props={data} />
  <Form props={data} />
</div>
