<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/police-matters/crime-prevention
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Tips and resources for ensuring public safety and order.`}
  </div>
  <Info props={data} />
  <DocumentHub props={data} />
</div>
