// Auto-generated by project_EngineerV2.ts on Wed Sep 24 2025 13:36:36 GMT+0800 (Philippine Standard Time)
// This file contains the site's navigation structure and metadata for build-time import.

export const siteInfo = {
  "targetPath": "SQP",
  "friendlyName": "Township of San Quintin, Pangasinan",
  "abstract": "San Quintin is a third-class municipality in Pangasinan, Philippines, known for its agricultural products like rice, onions, and corn, and its natural attractions, such as the Dipalo River Park and waterfalls like Katukakan Falls and Dipalo Falls. The town was settled by Ilocano immigrants who replaced earlier, fierce tribes and was organized under the leadership of Don Quintin Lictawa."
};

export const navigation = [
  {
    "slug": "citizen-services",
    "navTitle": "Citizen",
    "icon": "Users",
    "description": "Access essential services and manage personal records from one portal.",
    "children": [
      {
        "slug": "citizen-services/profiles",
        "navTitle": "My Profile",
        "icon": "User",
        "description": "Manage your personal information, linked IDs, and account settings.",
        "children": [
          {
            "slug": "citizen-services/profiles/account-settings",
            "navTitle": "Account",
            "icon": "Lock",
            "description": "Update your login credentials and security settings."
          },
          {
            "slug": "citizen-services/profiles/linked-ids",
            "navTitle": "Linked IDs",
            "icon": "IdCard",
            "description": "Link your PinoyID and other government IDs for seamless transactions."
          },
          {
            "slug": "citizen-services/profiles/contact-info",
            "navTitle": "Contact Info",
            "icon": "Phone",
            "description": "Update your contact details for official notifications."
          }
        ]
      },
      {
        "slug": "citizen-services/civil-registry",
        "navTitle": "Civil Registry",
        "icon": "BookUser",
        "description": "Request official copies of birth, marriage, and death certificates.",
        "children": [
          {
            "slug": "citizen-services/civil-registry/birth-certificate",
            "navTitle": "Birth Certificate",
            "icon": "FileBadge",
            "description": "Apply for a certified true copy of a birth certificate."
          },
          {
            "slug": "citizen-services/civil-registry/marriage-certificate",
            "navTitle": "Marriage Certificate",
            "icon": "Ring",
            "description": "Apply for a certified true copy of a marriage certificate."
          },
          {
            "slug": "citizen-services/civil-registry/death-certificate",
            "navTitle": "Death Certificate",
            "icon": "Tombstone",
            "description": "Apply for a certified true copy of a death certificate."
          }
        ]
      },
      {
        "slug": "citizen-services/community-feedback",
        "navTitle": "Feedback",
        "icon": "MessagesSquare",
        "description": "Submit suggestions, complaints, or reports to the LGU.",
        "children": [
          {
            "slug": "citizen-services/community-feedback/suggestion-box",
            "navTitle": "Suggestions",
            "icon": "Lightbulb",
            "description": "Anonymously submit ideas and suggestions for community improvement."
          },
          {
            "slug": "citizen-services/community-feedback/citizen-concerns",
            "navTitle": "Concerns",
            "icon": "AlertCircle",
            "description": "Report issues and concerns on LGU services or staff."
          }
        ]
      }
    ]
  },
  {
    "slug": "business-services",
    "navTitle": "Business",
    "icon": "Store",
    "description": "A one-stop shop for business permits, taxation, and economic development.",
    "children": [
      {
        "slug": "business-services/bpls-portal",
        "navTitle": "BPLS",
        "icon": "FileText",
        "description": "Business Permit and Licensing System for application, renewal, and tracking.",
        "children": [
          {
            "slug": "business-services/bpls-portal/new-application",
            "navTitle": "New",
            "icon": "FilePlus2",
            "description": "Guided process to register a new business."
          },
          {
            "slug": "business-services/bpls-portal/renewal",
            "navTitle": "Renewal",
            "icon": "RefreshCw",
            "description": "Streamlined process for renewing existing business permits."
          },
          {
            "slug": "business-services/bpls-portal/track-bpls",
            "navTitle": "Status",
            "icon": "Activity",
            "description": "Monitor the real-time status of your BPLS application."
          }
        ]
      },
      {
        "slug": "business-services/market-management",
        "navTitle": "Market",
        "icon": "ShoppingBasket",
        "description": "Services for public market stallholders and vendors.",
        "children": [
          {
            "slug": "business-services/market-management/payments",
            "navTitle": "Payments",
            "icon": "Wallet",
            "description": "Pay your monthly stall rental fees online."
          },
          {
            "slug": "business-services/market-management/requests",
            "navTitle": "Requests",
            "icon": "Wrench",
            "description": "Submit maintenance or service requests for your stall."
          }
        ]
      },
      {
        "slug": "business-services/economic-planning",
        "navTitle": "Planning",
        "icon": "GitBranch",
        "description": "Information on local economic development and zoning plans.",
        "children": [
          {
            "slug": "business-services/economic-planning/land-use",
            "navTitle": "Land Use",
            "icon": "Landmark",
            "description": "View the official land use and zoning plan of the community."
          },
          {
            "slug": "business-services/economic-planning/investment-opportunities",
            "navTitle": "Investments",
            "icon": "Building",
            "description": "Explore opportunities for business and investment in the LGU."
          }
        ]
      }
    ]
  },
  {
    "slug": "safety-alerts",
    "navTitle": "Safety",
    "icon": "Siren",
    "description": "Emergency alerts, incident reporting, and public safety information.",
    "children": [
      {
        "slug": "safety-alerts/emergency-alerts",
        "navTitle": "Alerts",
        "icon": "Megaphone",
        "description": "Receive timely and verified emergency information from the LDRRMO.",
        "children": [
          {
            "slug": "safety-alerts/emergency-alerts/live-updates",
            "navTitle": "Live Updates",
            "icon": "CloudSun",
            "description": "See the latest news on weather, class suspensions, and emergency advisories."
          },
          {
            "slug": "safety-alerts/emergency-alerts/hazard-maps",
            "navTitle": "Hazard Maps",
            "icon": "Map",
            "description": "Interactive maps showing real-time hazards and affected areas."
          },
          {
            "slug": "safety-alerts/emergency-alerts/evacuation-centers",
            "navTitle": "Evac Centers",
            "icon": "MapPinned",
            "description": "Locate and get directions to the nearest evacuation centers."
          }
        ]
      },
      {
        "slug": "safety-alerts/incident-report",
        "navTitle": "Report",
        "icon": "PhoneForwarded",
        "description": "Report incidents and concerns to LGU responders.",
        "children": [
          {
            "slug": "safety-alerts/incident-report/submit-report",
            "navTitle": "Submit",
            "icon": "Send",
            "description": "Submit a report with your location, photos, and videos."
          },
          {
            "slug": "safety-alerts/incident-report/track-report",
            "navTitle": "Track",
            "icon": "ClipboardCheck",
            "description": "Monitor the status of your submitted reports."
          }
        ]
      },
      {
        "slug": "safety-alerts/police-matters",
        "navTitle": "Police",
        "icon": "ShieldAlert",
        "description": "Information on police matters and public order.",
        "children": [
          {
            "slug": "safety-alerts/police-matters/blotter-request",
            "navTitle": "Blotter",
            "icon": "FileSearch",
            "description": "Request a copy of a blotter report."
          },
          {
            "slug": "safety-alerts/police-matters/crime-prevention",
            "navTitle": "Crime Prevention",
            "icon": "Handcuffs",
            "description": "Tips and resources for ensuring public safety and order."
          }
        ]
      }
    ]
  },
  {
    "slug": "health-welfare",
    "navTitle": "Health",
    "icon": "HeartPulse",
    "description": "Public health, social welfare, and community-based programs.",
    "children": [
      {
        "slug": "health-welfare/health-services",
        "navTitle": "Health",
        "icon": "Stethoscope",
        "description": "Access RHU services and manage your health records.",
        "children": [
          {
            "slug": "health-welfare/health-services/appointments",
            "navTitle": "Appointments",
            "icon": "CalendarPlus",
            "description": "Book, reschedule, or cancel health center appointments."
          },
          {
            "slug": "health-welfare/health-services/vaxcert",
            "navTitle": "VaxCert",
            "icon": "QrCode",
            "description": "Generate and download your official vaccination certificate with your PinoyID."
          }
        ]
      },
      {
        "slug": "health-welfare/social-welfare",
        "navTitle": "Welfare",
        "icon": "HandHelping",
        "description": "Programs and benefits for senior citizens, PWDs, and other community sectors.",
        "children": [
          {
            "slug": "health-welfare/social-welfare/senior-citizen",
            "navTitle": "Senior",
            "icon": "PersonStanding",
            "description": "Notifications and services for senior citizens."
          },
          {
            "slug": "health-welfare/social-welfare/pwd",
            "navTitle": "PWD",
            "icon": "Accessibility",
            "description": "Programs and benefits for Persons with Disabilities."
          },
          {
            "slug": "health-welfare/social-welfare/4ps",
            "navTitle": "4Ps",
            "icon": "HandCoins",
            "description": "Information on the Pantawid Pamilyang Pilipino Program (4Ps)."
          }
        ]
      }
    ]
  },
  {
    "slug": "education",
    "navTitle": "Education",
    "icon": "GraduationCap",
    "description": "School-related news, programs, and updates for students and parents.",
    "children": [
      {
        "slug": "education/school-news",
        "navTitle": "News",
        "icon": "Newspaper",
        "description": "Official announcements on classes, events, and school programs.",
        "children": [
          {
            "slug": "education/school-news/class-cancellation",
            "navTitle": "Cancellations",
            "icon": "CloudRain",
            "description": "Latest news on class suspensions due to weather or other events."
          },
          {
            "slug": "education/school-news/youth-activities",
            "navTitle": "Youth Activities",
            "icon": "Calendar",
            "description": "Scheduled events and programs for the youth."
          }
        ]
      },
      {
        "slug": "education/sk-federation",
        "navTitle": "SK Federation",
        "icon": "Trophy",
        "description": "Official announcements and programs from the Sangguniang Kabataan Federation.",
        "children": [
          {
            "slug": "education/sk-federation/projects",
            "navTitle": "Projects",
            "icon": "ClipboardCheck",
            "description": "View ongoing and completed projects of the SK Federation."
          },
          {
            "slug": "education/sk-federation/forms",
            "navTitle": "Forms",
            "icon": "Download",
            "description": "Downloadable forms for SK-related activities and programs."
          }
        ]
      }
    ]
  },
  {
    "slug": "local-gov",
    "navTitle": "LGU Offices",
    "icon": "Building",
    "description": "Directory and information about local government offices and officials.",
    "children": [
      {
        "slug": "local-gov/executive",
        "navTitle": "Executive",
        "icon": "UserCrown",
        "description": "Information about the offices of the Mayor and Vice-Mayor.",
        "children": [
          {
            "slug": "local-gov/executive/mayors-office",
            "navTitle": "Mayor's Office",
            "icon": "Mail",
            "description": "Announcements and contact details for the Mayor's Office."
          },
          {
            "slug": "local-gov/executive/vice-mayors-office",
            "navTitle": "Vice-Mayor's Office",
            "icon": "Mail",
            "description": "Information and updates from the Vice-Mayor's Office."
          }
        ]
      },
      {
        "slug": "local-gov/legislative",
        "navTitle": "Legislative",
        "icon": "Gavel",
        "description": "Official documents and news from the Sangguniang Bayan.",
        "children": [
          {
            "slug": "local-gov/legislative/ordinances",
            "navTitle": "Ordinances",
            "icon": "FileText",
            "description": "View and search for local ordinances and resolutions."
          },
          {
            "slug": "local-gov/legislative/meetings",
            "navTitle": "Meetings",
            "icon": "Calendar",
            "description": "View the schedule of legislative meetings."
          }
        ]
      },
      {
        "slug": "local-gov/barangay-affairs",
        "navTitle": "Barangay",
        "icon": "LandPlot",
        "description": "Centralized hub for all barangay-related information and services.",
        "children": [
          {
            "slug": "local-gov/barangay-affairs/directory",
            "navTitle": "Directory",
            "icon": "BookCopy",
            "description": "Find contact information for all barangays in the community."
          },
          {
            "slug": "local-gov/barangay-affairs/news",
            "navTitle": "News",
            "icon": "Newspaper",
            "description": "Latest news and announcements from all barangays."
          }
        ]
      },
      {
        "slug": "local-gov/departments",
        "navTitle": "Directory",
        "icon": "BookCopy",
        "description": "Find contact information and services for all LGU departments.",
        "children": [
          {
            "slug": "local-gov/departments/mayor",
            "navTitle": "Mayor",
            "icon": "UserCrown",
            "description": "Details for Mayor's office."
          },
          {
            "slug": "local-gov/departments/engineering",
            "navTitle": "Engineering",
            "icon": "Hammer",
            "description": "Details for Engineering Department."
          },
          {
            "slug": "local-gov/departments/tourism",
            "navTitle": "Tourism",
            "icon": "MapPinned",
            "description": "Details for Department of Tourism."
          }
        ]
      }
    ]
  },
  {
    "slug": "public-info",
    "navTitle": "Info & News",
    "icon": "Megaphone",
    "description": "Official announcements, news, and updates for the public.",
    "children": [
      {
        "slug": "public-info/news-media",
        "navTitle": "News Hub",
        "icon": "Newspaper",
        "description": "A centralized hub for all official LGU news.",
        "children": [
          {
            "slug": "public-info/news-media/latest-news",
            "navTitle": "Latest News",
            "icon": "MessageSquare",
            "description": "The latest news and announcements from the LGU."
          },
          {
            "slug": "public-info/news-media/miscellaneous",
            "navTitle": "Miscellaneous",
            "icon": "Folder",
            "description": "General news and information that is not category-specific."
          }
        ]
      },
      {
        "slug": "public-info/lgu-events",
        "navTitle": "Events",
        "icon": "Calendar",
        "description": "Official schedule of LGU activities, ceremonies, and events.",
        "children": [
          {
            "slug": "public-info/lgu-events/upcoming-events",
            "navTitle": "Upcoming",
            "icon": "CalendarClock",
            "description": "Calendar view of all scheduled LGU activities."
          },
          {
            "slug": "public-info/lgu-events/event-photos",
            "navTitle": "Photos",
            "icon": "Camera",
            "description": "Photo and video galleries of past LGU events."
          }
        ]
      },
      {
        "slug": "public-info/contact",
        "navTitle": "Contact Us",
        "icon": "Phone",
        "description": "Find contact information for LGU offices and send a message.",
        "children": [
          {
            "slug": "public-info/contact/contact-form",
            "navTitle": "Form",
            "icon": "Mail",
            "description": "Send a direct message to the LGU for inquiries or feedback."
          },
          {
            "slug": "public-info/contact/social-media",
            "navTitle": "Socials",
            "icon": "Share",
            "description": "Links to the official LGU social media pages."
          }
        ]
      }
    ]
  }
];
