<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /intel-command/fusion-analytics-center
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Chart from '$lib/Components/Templates/Chart.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `AI-driven tools for deep analysis across multiple intelligence disciplines.`}
  </div>
  <Dashboard props={data} />
  <Chart props={data} />
</div>
