<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/history/background
  export let data: any;

import Article from '$lib/Components/Templates/Article.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Additional context on the purpose and early development of ICI.`}
  </div>
  <Article props={data} />
  <Info props={data} />
</div>
