<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/police-matters/blotter-request
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Request a copy of a blotter report.`}
  </div>
  <Form props={data} />
  <Tracker props={data} />
</div>
