<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/search
  export let data: any;

import Search from '$lib/Components/Templates/Search.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Results from '$lib/Components/Templates/Results.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Perform a detailed search for specific projects using keywords, project IDs, or contractors.`}
  </div>
  <Search props={data} />
  <Table props={data} />
  <Results props={data} />
</div>
