<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /strategic-command/inter-agency-portal/task-force-local
  export let data: any;

import Feed from '$lib/Components/Templates/Feed.svelte';
import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
import Calendar from '$lib/Components/Templates/Calendar.svelte';
import Sms from '$lib/Components/Templates/Sms.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Joint operations planning and intelligence sharing with local law enforcement.`}
  </div>
  <Feed props={data} />
  <DocumentHub props={data} />
  <Calendar props={data} />
  <Sms props={data} />
</div>
