<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigations-legal/prosecution-support
  export let data: any;

import Report from '$lib/Components/Templates/Report.svelte';
import Checklist from '$lib/Components/Templates/Checklist.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Prepare and transmit evidence packages and case summaries to the Department of Justice.`}
  </div>
  <Report props={data} />
  <Checklist props={data} />
  <Form props={data} />
  <DocumentHub props={data} />
</div>
