<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /directory/key-officials
  export let data: any;

import Profile from '$lib/Components/Templates/Profile.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Directory of the PDEA Director General, Deputy DGs, and Service Directors.`}
  </div>
  <Profile props={data} />
  <Table props={data} />
</div>
