<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /saln-declarations/analytics
  export let data: any;

import Chart from '$lib/Components/Templates/Chart.svelte';
import KpiDeck from '$lib/Components/Templates/KpiDeck.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `View trends and analytics on net worth changes and business interests declared in SALN documents.`}
  </div>
  <Chart props={data} />
  <KpiDeck props={data} />
  <Filter props={data} />
</div>
