<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/history
  export let data: any;

import Article from '$lib/Components/Templates/Article.svelte';
import Timeline from '$lib/Components/Templates/Timeline.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `The historical background of ICI, its formation, and objectives.`}
  </div>
  <Article props={data} />
  <Timeline props={data} />
  <Info props={data} />
</div>
