<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /saln-declarations/search-officials
  export let data: any;

import Search from '$lib/Components/Templates/Search.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Search for officials by name or agency to view their SALN submissions.`}
  </div>
  <Search props={data} />
  <Table props={data} />
  <Profile props={data} />
</div>
