<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services/profiles/linked-ids
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Camera from '$lib/Components/Templates/Camera.svelte';
import QrCode from '$lib/Components/Templates/QrCode.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Link your PinoyID and other government IDs for seamless transactions.`}
  </div>
  <Form props={data} />
  <Camera props={data} />
  <QrCode props={data} />
  <Profile props={data} />
</div>
