<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /local-gov/departments/mayor
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Details for Mayor's office.`}
  </div>
  <Info props={data} />
  <Profile props={data} />
</div>
