// Auto-generated by project_EngineerV2.ts on Tue Sep 23 2025 09:37:57 GMT+0800 (Philippine Standard Time)
// This file contains the site's navigation structure and metadata for build-time import.

export const siteInfo = {
  "targetPath": "ICI",
  "friendlyName": "Independent Committee on Infrastructure"
};

export const navigation = [
  {
    "slug": "dashboard",
    "navTitle": "Dashboard",
    "icon": "LayoutDashboard",
    "description": "The central hub of the ICI system, providing a live overview of infrastructure monitoring, corruption alerts, and citizen engagement."
  },
  {
    "slug": "about",
    "navTitle": "About",
    "icon": "Info",
    "description": "Learn about the history, mandate, and leadership structure of the Independent Commission for Infrastructure (ICI).",
    "children": [
      {
        "slug": "about/history",
        "navTitle": "History",
        "icon": "BookOpen",
        "description": "The historical background of ICI, its formation, and objectives."
      },
      {
        "slug": "about/mandate",
        "navTitle": "Mandate",
        "icon": "Gavel",
        "description": "An overview of ICI’s legal authority, powers, and scope of investigations."
      },
      {
        "slug": "about/leadership",
        "navTitle": "Leadership",
        "icon": "Users",
        "description": "Profiles of the commissioners, secretariat, and organizational structure."
      }
    ]
  },
  {
    "slug": "corruption-findings",
    "navTitle": "Findings",
    "icon": "AlertTriangle",
    "description": "Access dashboards and detailed reports on corruption findings and anomalies in infrastructure projects.",
    "children": [
      {
        "slug": "corruption-findings/fund-misuse",
        "navTitle": "Fund Misuse",
        "icon": "Landmark",
        "description": "Alerts and records concerning misuse of public funds."
      },
      {
        "slug": "corruption-findings/procurement-issues",
        "navTitle": "Procurement",
        "icon": "FileText",
        "description": "Reports on irregularities in procurement processes."
      },
      {
        "slug": "corruption-findings/project-delays",
        "navTitle": "Delays",
        "icon": "Clock",
        "description": "Tracking project delays, cost overruns, and impact analysis."
      }
    ]
  },
  {
    "slug": "projects",
    "navTitle": "Projects",
    "icon": "Construction",
    "description": "Monitor the status, budget, and progress of all registered public infrastructure projects across the Philippines.",
    "children": [
      {
        "slug": "projects/by-status",
        "navTitle": "By Status",
        "icon": "ClipboardCheck",
        "description": "Filter and view projects based on their current status: ongoing, completed, delayed, or flagged.",
        "children": [
          {
            "slug": "projects/by-status/ongoing",
            "navTitle": "Ongoing",
            "icon": "PlayCircle",
            "description": "A list of all projects currently in progress."
          },
          {
            "slug": "projects/by-status/completed",
            "navTitle": "Completed",
            "icon": "CheckCircle2",
            "description": "A repository of successfully completed infrastructure projects."
          },
          {
            "slug": "projects/by-status/delayed",
            "navTitle": "Delayed",
            "icon": "Clock",
            "description": "Projects that have exceeded their projected timelines."
          },
          {
            "slug": "projects/by-status/flagged",
            "navTitle": "Flagged",
            "icon": "Flag",
            "description": "Projects flagged for potential issues, anomalies, or corruption indicators."
          }
        ]
      },
      {
        "slug": "projects/by-region",
        "navTitle": "By Region",
        "icon": "MapPin",
        "description": "Explore projects geographically, from national to local levels."
      },
      {
        "slug": "projects/search",
        "navTitle": "Project Search",
        "icon": "Search",
        "description": "Perform a detailed search for specific projects using keywords, project IDs, or contractors."
      }
    ]
  },
  {
    "slug": "saln-declarations",
    "navTitle": "SALN",
    "icon": "ShieldCheck",
    "description": "Access and review the Statement of Assets, Liabilities, and Net Worth (SALN) of public officials involved in infrastructure projects.",
    "children": [
      {
        "slug": "saln-declarations/search-officials",
        "navTitle": "Search Officials",
        "icon": "Search",
        "description": "Search for officials by name or agency to view their SALN submissions."
      },
      {
        "slug": "saln-declarations/by-agency",
        "navTitle": "By Agency",
        "icon": "Building2",
        "description": "Browse SALN submissions from officials grouped by their respective government agencies."
      },
      {
        "slug": "saln-declarations/analytics",
        "navTitle": "Analytics",
        "icon": "PieChart",
        "description": "View trends and analytics on net worth changes and business interests declared in SALN documents."
      },
      {
        "slug": "saln-declarations/request-guide",
        "navTitle": "Request Guide",
        "icon": "HelpCircle",
        "description": "Information and guidelines on the official process for requesting a copy of a SALN."
      }
    ]
  },
  {
    "slug": "soundboard",
    "navTitle": "Soundboard",
    "icon": "MessageSquare",
    "description": "A platform for citizen engagement, feedback, and whistleblowing.",
    "children": [
      {
        "slug": "soundboard/public-feedback",
        "navTitle": "Feedback",
        "icon": "MessageCircle",
        "description": "Submit and review public feedback on ongoing projects."
      },
      {
        "slug": "soundboard/whistleblower-reports",
        "navTitle": "Whistleblowers",
        "icon": "ShieldAlert",
        "description": "Secure reporting for whistleblowers to flag irregularities."
      }
    ]
  },
  {
    "slug": "agencies",
    "navTitle": "Agencies",
    "icon": "Building2",
    "description": "Browse the agencies investigated and their related projects.",
    "children": [
      {
        "slug": "agencies/dpwh",
        "navTitle": "DPWH",
        "icon": "Hammer",
        "description": "Department of Public Works & Highways"
      },
      {
        "slug": "agencies/dotr",
        "navTitle": "DOTr",
        "icon": "BusFront",
        "description": "Department of Transportation"
      },
      {
        "slug": "agencies/dict",
        "navTitle": "DICT",
        "icon": "Server",
        "description": "Department of ICT"
      },
      {
        "slug": "agencies/psa",
        "navTitle": "PSA",
        "icon": "Database",
        "description": "Philippine Statistics Authority"
      },
      {
        "slug": "agencies/doh",
        "navTitle": "DOH",
        "icon": "Hospital",
        "description": "Department of Health"
      }
    ]
  },
  {
    "slug": "investigation-reports",
    "navTitle": "Reports",
    "icon": "FileText",
    "description": "Access all investigation reports, case studies, and open datasets for transparency.",
    "children": [
      {
        "slug": "investigation-reports/annual-reports",
        "navTitle": "Annual",
        "icon": "Calendar",
        "description": "Annual & thematic reports."
      },
      {
        "slug": "investigation-reports/case-studies",
        "navTitle": "Case Studies",
        "icon": "FileSearch",
        "description": "In-depth case studies and investigations."
      },
      {
        "slug": "investigation-reports/open-data",
        "navTitle": "Open Data",
        "icon": "Database",
        "description": "Datasets and open access files."
      }
    ]
  }
];
