<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /intel-command/fusion-analytics-center/geospatial-intelligence
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import Chart from '$lib/Components/Templates/Chart.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
import Gps from '$lib/Components/Templates/Gps.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Map and analyze drug routes, clandestine laboratories, and operational hotspots.`}
  </div>
  <Map props={data} />
  <Chart props={data} />
  <Report props={data} />
  <Gps props={data} />
</div>
