<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigations-legal/unified-case-management/syndicate-cases
  export let data: any;

import Chart from '$lib/Components/Templates/Chart.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Investigations focused on dismantling entire drug trafficking organizations.`}
  </div>
  <Chart props={data} />
  <Table props={data} />
  <Report props={data} />
</div>
