<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /strategic-command/asset-forfeiture
  export let data: any;

import Chart from '$lib/Components/Templates/Chart.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Track financial investigations with AMLC and manage seized assets from drug syndicates.`}
  </div>
  <Chart props={data} />
  <Table props={data} />
  <Form props={data} />
</div>
