<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /health-welfare/health-services/appointments
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Calendar from '$lib/Components/Templates/Calendar.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Book, reschedule, or cancel health center appointments.`}
  </div>
  <Form props={data} />
  <Calendar props={data} />
</div>
