<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigation-reports/annual-reports
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Download from '$lib/Components/Templates/Download.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Annual & thematic reports.`}
  </div>
  <Table props={data} />
  <Download props={data} />
</div>
