<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /corruption-findings/procurement-issues
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Chart from '$lib/Components/Templates/Chart.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Reports on irregularities in procurement processes.`}
  </div>
  <Table props={data} />
  <Chart props={data} />
  <Filter props={data} />
</div>
