<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Access essential services and manage personal records from one portal.`}
  </div>
  <Dashboard props={data} />
  <Profile props={data} />
</div>
