<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /education/sk-federation/forms
  export let data: any;

import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Downloadable forms for SK-related activities and programs.`}
  </div>
  <DocumentHub props={data} />
</div>
