<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services/bpls-portal
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Business Permit and Licensing System for application, renewal, and tracking.`}
  </div>
  <Dashboard props={data} />
  <Form props={data} />
  <Tracker props={data} />
</div>
