<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services/profiles
  export let data: any;

import Profile from '$lib/Components/Templates/Profile.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Manage your personal information, linked IDs, and account settings.`}
  </div>
  <Profile props={data} />
  <Form props={data} />
</div>
