<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /education/school-news/class-cancellation
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Latest news on class suspensions due to weather or other events.`}
  </div>
  <Info props={data} />
</div>
