<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /local-gov/departments
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Search from '$lib/Components/Templates/Search.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Find contact information and services for all LGU departments.`}
  </div>
  <Table props={data} />
  <Search props={data} />
</div>
