<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /education/school-news
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Official announcements on classes, events, and school programs.`}
  </div>
  <Dashboard props={data} />
  <Table props={data} />
</div>
