<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services/bpls-portal/renewal
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Upload from '$lib/Components/Templates/Upload.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Streamlined process for renewing existing business permits.`}
  </div>
  <Form props={data} />
  <Upload props={data} />
</div>
