<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /local-gov
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Directory and information about local government offices and officials.`}
  </div>
  <Info props={data} />
  <Table props={data} />
</div>
