<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/by-status/completed
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
import Gallery from '$lib/Components/Templates/Gallery.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `A repository of successfully completed infrastructure projects.`}
  </div>
  <Table props={data} />
  <Filter props={data} />
  <Gallery props={data} />
</div>
