<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /forensics-evidence/dcoc
  export let data: any;

import Tracker from '$lib/Components/Templates/Tracker.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
import QrCode from '$lib/Components/Templates/QrCode.svelte';
import Camera from '$lib/Components/Templates/Camera.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Immutable, tamper-proof log for all evidence handling, compliant with R.A. 9165.`}
  </div>
  <Tracker props={data} />
  <Form props={data} />
  <Report props={data} />
  <QrCode props={data} />
  <Camera props={data} />
</div>
