<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /corruption-findings/project-delays
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import LineChart from '$lib/Components/Templates/LineChart.svelte';
import Timeline from '$lib/Components/Templates/Timeline.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Tracking project delays, cost overruns, and impact analysis.`}
  </div>
  <Table props={data} />
  <LineChart props={data} />
  <Timeline props={data} />
</div>
