<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services/civil-registry
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Request official copies of birth, marriage, and death certificates.`}
  </div>
  <Info props={data} />
  <Form props={data} />
</div>
