<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /corruption-findings
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import KpiDeck from '$lib/Components/Templates/KpiDeck.svelte';
import BarChart from '$lib/Components/Templates/BarChart.svelte';
import LineChart from '$lib/Components/Templates/LineChart.svelte';
import PieChart from '$lib/Components/Templates/PieChart.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Access dashboards and detailed reports on corruption findings and anomalies in infrastructure projects.`}
  </div>
  <Dashboard props={data} />
  <KpiDeck props={data} />
  <BarChart props={data} />
  <LineChart props={data} />
  <PieChart props={data} />
</div>
