<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /soundboard/whistleblower-reports
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Upload from '$lib/Components/Templates/Upload.svelte';
import Faq from '$lib/Components/Templates/Faq.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Secure reporting for whistleblowers to flag irregularities.`}
  </div>
  <Form props={data} />
  <Upload props={data} />
  <Faq props={data} />
</div>
