<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services/profiles/account-settings
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Update your login credentials and security settings.`}
  </div>
  <Form props={data} />
</div>
