<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/incident-report
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Report incidents and concerns to LGU responders.`}
  </div>
  <Form props={data} />
  <Map props={data} />
</div>
