<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /dashboard/overview
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import KpiDeck from '$lib/Components/Templates/KpiDeck.svelte';
import Chart from '$lib/Components/Templates/Chart.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `A snapshot of key metrics and summary insights from across the ICI system.`}
  </div>
  <Info props={data} />
  <KpiDeck props={data} />
  <Chart props={data} />
</div>
