<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /forensics-evidence/laboratory-services
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Manage drug testing, chemical analysis, and results from forensic chemistry labs.`}
  </div>
  <Dashboard props={data} />
  <Table props={data} />
  <Form props={data} />
</div>
