<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigations-legal/unified-case-management/hvt-cases
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Specialized tracking for cases involving top-tier drug personalities.`}
  </div>
  <Table props={data} />
  <Tracker props={data} />
  <Profile props={data} />
</div>
