<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `A one-stop shop for business permits, taxation, and economic development.`}
  </div>
  <Dashboard props={data} />
  <Info props={data} />
</div>
