<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /agencies/dpwh
  export let data: any;

import Profile from '$lib/Components/Templates/Profile.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
import Download from '$lib/Components/Templates/Download.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Department of Public Works & Highways`}
  </div>
  <Profile props={data} />
  <Table props={data} />
  <Map props={data} />
  <Download props={data} />
</div>
