<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /intel-command/target-dossiers
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Profile from '$lib/Components/Templates/Profile.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Dynamic profiles of HVTs, syndicates, and their networks, updated in real-time.`}
  </div>
  <Dashboard props={data} />
  <Profile props={data} />
  <Table props={data} />
</div>
