<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /saln-declarations
  export let data: any;

import KpiDeck from '$lib/Components/Templates/KpiDeck.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Search from '$lib/Components/Templates/Search.svelte';
import Download from '$lib/Components/Templates/Download.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Access and review the Statement of Assets, Liabilities, and Net Worth (SALN) of public officials involved in infrastructure projects.`}
  </div>
  <KpiDeck props={data} />
  <Table props={data} />
  <Search props={data} />
  <Download props={data} />
</div>
