<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services/economic-planning/land-use
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `View the official land use and zoning plan of the community.`}
  </div>
  <Map props={data} />
  <Info props={data} />
</div>
