<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /corruption-findings/fund-misuse
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
import Download from '$lib/Components/Templates/Download.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Alerts and records concerning misuse of public funds.`}
  </div>
  <Table props={data} />
  <Filter props={data} />
  <Download props={data} />
</div>
