<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /operations-command
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Plan, authorize, and command all national and regional counter-narcotics field operations.`}
  </div>
  <Dashboard props={data} />
  <Map props={data} />
  <Tracker props={data} />
</div>
