<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Accordion from '$lib/Components/Templates/Accordion.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Learn about the history, mandate, and leadership structure of the Independent Commission for Infrastructure (ICI).`}
  </div>
  <Info props={data} />
  <Accordion props={data} />
</div>
