<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /strategic-command
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `High-level policy support, asset forfeiture, and seamless collaboration with local and international partners.`}
  </div>
  <Dashboard props={data} />
  <Info props={data} />
</div>
