<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /public-info/lgu-events
  export let data: any;

import Calendar from '$lib/Components/Templates/Calendar.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Official schedule of LGU activities, ceremonies, and events.`}
  </div>
  <Calendar props={data} />
  <Table props={data} />
</div>
