<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /forensics-evidence/digital-forensics-unit/mobile-forensics
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
import DocumentHub from '$lib/Components/Templates/DocumentHub.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Case management for analysis of seized mobile phones and tablets.`}
  </div>
  <Table props={data} />
  <Tracker props={data} />
  <DocumentHub props={data} />
</div>
