<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Emergency alerts, incident reporting, and public safety information.`}
  </div>
  <Dashboard props={data} />
  <Info props={data} />
  <Map props={data} />
</div>
