<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /strategic-command/inter-agency-portal/international-liaison
  export let data: any;

import Chat from '$lib/Components/Templates/Chat.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
import Sms from '$lib/Components/Templates/Sms.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Secure communication channel for coordinating with international partners.`}
  </div>
  <Chat props={data} />
  <Table props={data} />
  <Report props={data} />
  <Sms props={data} />
</div>
