<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /dashboard
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import KpiDeck from '$lib/Components/Templates/KpiDeck.svelte';
import ActivityFeed from '$lib/Components/Templates/ActivityFeed.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `The central hub of the ICI system, providing a live overview of infrastructure monitoring, corruption alerts, and citizen engagement.`}
  </div>
  <Dashboard props={data} />
  <KpiDeck props={data} />
  <ActivityFeed props={data} />
  <Map props={data} />
</div>
