<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/by-status
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Filter and view projects based on their current status: ongoing, completed, delayed, or flagged.`}
  </div>
  <Table props={data} />
  <Filter props={data} />
</div>
