<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /soundboard/public-feedback
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Search from '$lib/Components/Templates/Search.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Submit and review public feedback on ongoing projects.`}
  </div>
  <Form props={data} />
  <Table props={data} />
  <Search props={data} />
</div>
