<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /forensics-evidence
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Ensure the scientific and legal integrity of all seized evidence from collection to court presentation.`}
  </div>
  <Dashboard props={data} />
  <Table props={data} />
  <Info props={data} />
</div>
