<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /intel-command/fusion-analytics-center/cyber-intelligence
  export let data: any;

import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Feed from '$lib/Components/Templates/Feed.svelte';
import Chat from '$lib/Components/Templates/Chat.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Monitor darknet markets, encrypted communications, and online narcotics trafficking.`}
  </div>
  <Dashboard props={data} />
  <Feed props={data} />
  <Chat props={data} />
</div>
