<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/mandate/legal-authority
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Faq from '$lib/Components/Templates/Faq.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Legal frameworks and mandates enabling ICI’s operations.`}
  </div>
  <Info props={data} />
  <Faq props={data} />
</div>
