<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /operations-command/field-operations-log
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Comprehensive repository of all planned, ongoing, and completed field operations.`}
  </div>
  <Table props={data} />
  <Info props={data} />
  <Map props={data} />
</div>
