<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /public-info/lgu-events/event-photos
  export let data: any;

import Gallery from '$lib/Components/Templates/Gallery.svelte';
import Upload from '$lib/Components/Templates/Upload.svelte';
import Camera from '$lib/Components/Templates/Camera.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Photo and video galleries of past LGU events.`}
  </div>
  <Gallery props={data} />
  <Upload props={data} />
  <Camera props={data} />
</div>
