<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /operations-command/field-operations-log/buy-bust-ops
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Tracker from '$lib/Components/Templates/Tracker.svelte';
import Report from '$lib/Components/Templates/Report.svelte';
import Camera from '$lib/Components/Templates/Camera.svelte';
import QrCode from '$lib/Components/Templates/QrCode.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Manage and track all buy-bust operations nationwide.`}
  </div>
  <Table props={data} />
  <Tracker props={data} />
  <Report props={data} />
  <Camera props={data} />
  <QrCode props={data} />
</div>
