<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/by-status/ongoing
  export let data: any;

import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `A list of all projects currently in progress.`}
  </div>
  <Table props={data} />
  <Filter props={data} />
  <Map props={data} />
</div>
