<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services/economic-planning
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Map from '$lib/Components/Templates/Map.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Information on local economic development and zoning plans.`}
  </div>
  <Info props={data} />
  <Map props={data} />
</div>
