<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /health-welfare/health-services/vaxcert
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import QrCode from '$lib/Components/Templates/QrCode.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Generate and download your official vaccination certificate with your PinoyID.`}
  </div>
  <Form props={data} />
  <QrCode props={data} />
</div>
