<script lang="ts">
  import { createAvatar } from '@dicebear/core';
  // Importing multiple styles allows you to conditionally choose based on gender/age logic.
  // Lorelei generally offers more distinct features for subtle gender differentiation.
  import { lorelei } from '@dicebear/collection';

  // Define the props for the component
  let { displayName, age, gender } = $props<{
    displayName: string; // The name to use as a seed
    age: number;         // The age for age-based logic (e.g., scale)
    gender: 'Male' | 'Female' | 'Other'; // The gender for gender-based style/options
  }>();

  // Reactive declaration to re-generate avatars whenever props change
  // $derived ensures the SVG updates dynamically if displayName, age, or gender changes
  const avatarSvg = $derived(generateAvatarSvg({ fullname: displayName, age, gender }));

  /**
   * Generates an SVG string for a DiceBear avatars based on user properties.
   * This function encapsulates the logic for selecting styles and options.
   * @param user - An object containing fullname (for seed), age, and gender.
   * @returns The SVG string for the generated avatars.
   */
  function generateAvatarSvg(user: { fullname: string; age: number; gender: string }): string {
    const seed = user.fullname.replaceAll('|', ' '); // Clean the name for the seed

    let avatarOptions: Record<string, any> = {
      seed: seed,
      // Common aesthetic options for a consistent look across avatars
      backgroundColor: ['b6e3f4', 'c0aede', 'd1d4f9'], // Light, pleasant background colors
      size: 64, // Defines the base size of the SVG, matches w-16 (64px)
      scale: 100, // Default scale
    };

    // Initialize with a default style. Lorelei is generally versatile.
    let selectedStyle = lorelei;

    // --- Gender-based logic ---
    // The Lorelei style, while not having explicit 'gender' options, often produces
    // results that can be nudged by other options or by choosing a different style.
    if (user.gender === 'Female') {
      // For Lorelei, we can subtly influence by adjusting features.
      // Note: Lorelei doesn't have explicit 'hair' or 'facialHair' options like Avataaars.
      // If you switch to 'avataaars', you'd use options like:
      // selectedStyle = avataaars;
      // avatarOptions.top = ['longHair', 'shavedSides', 'bob', 'bun']; // Example female hair
    } else if (user.gender === 'Male') {
      // For Lorelei, male perception might be implied by lack of typically female traits.
      // If using 'avataaars', you'd use options like:
      // selectedStyle = avataaars;
      // avatarOptions.facialHairProbability = 80; // Higher chance of facial hair
      // avatarOptions.top = ['shortHair', 'theCaesar']; // Example male hair
    }
    // If 'Other' gender, keep neutral defaults or implement specific logic.

    // --- Age-based logic (limited with DiceBear's current styles) ---
    // DiceBear styles are not designed for detailed age variation.
    // We can use scale as a very rough visual indicator for younger individuals.
    if (user.age < 18) {
      avatarOptions.scale = 80; // Make the avatars slightly smaller to imply youth
      // You could also consider a different, more 'child-like' style if one exists
      // e.g., selectedStyle = pixelArt; (requires importing pixelArt from collection)
    } else if (user.age > 60) {
      // For older age, there are no direct options. You might choose specific color palettes
      // or subtly change feature probabilities if the selected style supports it.
      // For instance, perhaps a slightly less vibrant background color for older individuals.
      // avatarOptions.backgroundColor = ['e0e0e0', 'c0c0c0'];
    }

    // Generate the avatars SVG string
    return createAvatar(selectedStyle, avatarOptions).toString();
  }
</script>

<!-- The main container for the avatars.
     The 'w-full rounded-full' classes from your original code are applied here
     to maintain consistent sizing and appearance when replacing the existing tags.
     The 'overflow-hidden' ensures the rounded shape works correctly with the SVG.
-->
<div class="w-full rounded-full overflow-hidden ring ring-primary ring-offset-base-100 ring-offset-2 transition-all duration-300 ease-in-out group-hover:scale-110 group-hover:ring-secondary">
  <!-- Use @html to render the raw SVG string generated by DiceBear -->
  {@html avatarSvg}
</div>

<style>
  /* Basic styling for the SVG within the container to ensure it fills correctly */
  div :global(svg) {
    width: 100%;
    height: 100%;
    display: block; /* Removes extra space below the SVG */
  }
</style>
