<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services/market-management/payments
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Pay your monthly stall rental fees online.`}
  </div>
  <Form props={data} />
  <Table props={data} />
</div>
