<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /business-services/bpls-portal/new-application
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Checklist from '$lib/Components/Templates/Checklist.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Guided process to register a new business.`}
  </div>
  <Form props={data} />
  <Checklist props={data} />
</div>
