<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /citizen-services/community-feedback
  export let data: any;

import Form from '$lib/Components/Templates/Form.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Submit suggestions, complaints, or reports to the LGU.`}
  </div>
  <Form props={data} />
  <Info props={data} />
</div>
