<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /projects/by-region
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Filter from '$lib/Components/Templates/Filter.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Explore projects geographically, from national to local levels.`}
  </div>
  <Map props={data} />
  <Table props={data} />
  <Filter props={data} />
</div>
