<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /safety-alerts/emergency-alerts/evacuation-centers
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Gps from '$lib/Components/Templates/Gps.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Locate and get directions to the nearest evacuation centers.`}
  </div>
  <Map props={data} />
  <Table props={data} />
  <Gps props={data} />
</div>
