<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /operations-command/rtoc
  export let data: any;

import Map from '$lib/Components/Templates/Map.svelte';
import Dashboard from '$lib/Components/Templates/Dashboard.svelte';
import Chat from '$lib/Components/Templates/Chat.svelte';
import Gps from '$lib/Components/Templates/Gps.svelte';
import Camera from '$lib/Components/Templates/Camera.svelte';
import Sms from '$lib/Components/Templates/Sms.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Live situational awareness and command & control for all active missions.`}
  </div>
  <Map props={data} />
  <Dashboard props={data} />
  <Chat props={data} />
  <Gps props={data} />
  <Camera props={data} />
  <Sms props={data} />
</div>
