<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /local-gov/executive/vice-mayors-office
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Information and updates from the Vice-Mayor's Office.`}
  </div>
  <Info props={data} />
</div>
