<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /saln-declarations/request-guide
  export let data: any;

import Faq from '$lib/Components/Templates/Faq.svelte';
import Form from '$lib/Components/Templates/Form.svelte';
import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Information and guidelines on the official process for requesting a copy of a SALN.`}
  </div>
  <Faq props={data} />
  <Form props={data} />
  <Info props={data} />
</div>
