<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigation-reports/case-studies
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Download from '$lib/Components/Templates/Download.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `In-depth case studies and investigations.`}
  </div>
  <Info props={data} />
  <Download props={data} />
  <Table props={data} />
</div>
