<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /public-info/contact/social-media
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Links to the official LGU social media pages.`}
  </div>
  <Info props={data} />
</div>
