<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /investigation-reports/open-data
  export let data: any;

import Download from '$lib/Components/Templates/Download.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Search from '$lib/Components/Templates/Search.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Datasets and open access files.`}
  </div>
  <Download props={data} />
  <Table props={data} />
  <Search props={data} />
</div>
