<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /agencies
  export let data: any;

import List from '$lib/Components/Templates/List.svelte';
import Table from '$lib/Components/Templates/Table.svelte';
import Accordion from '$lib/Components/Templates/Accordion.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `Browse the agencies investigated and their related projects.`}
  </div>
  <List props={data} />
  <Table props={data} />
  <Accordion props={data} />
</div>
