<script lang="ts">
  // Auto-generated by project_EngineerV2.ts for path: /about/mandate
  export let data: any;

import Info from '$lib/Components/Templates/Info.svelte';
import Accordion from '$lib/Components/Templates/Accordion.svelte';
import Checklist from '$lib/Components/Templates/Checklist.svelte';
</script>

<div class="space-y-6 project-provider">
  <div class="project-page-intro  text-base-content/80 leading-relaxed">
    {@html `An overview of ICI’s legal authority, powers, and scope of investigations.`}
  </div>
  <Info props={data} />
  <Accordion props={data} />
  <Checklist props={data} />
</div>
